apiVersion: v1
kind: ServiceAccount
metadata:
  name: gitlab-runner-sa
  namespace: gitlab
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gitlab-runner-role
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: gitlab-runner-binding
subjects:
- kind: ServiceAccount
  name: gitlab-runner-sa
  namespace: gitlab
roleRef:
  kind: ClusterRole
  name: gitlab-runner-role
  apiGroup: rbac.authorization.k8s.io