Vagrant.configure("2") do |config|
  config.vm.define "mbelouarS" do |server|
    server.vm.box = "spox/ubuntu-arm"
    server.vm.box_version = "1.0.0"
    server.vm.hostname = "mbelouarS"

    # Networking
    server.vm.network "private_network", ip: "192.168.56.110"

    # Synced folder
    # server.vm.synced_folder "./token", "/vagrant/token"

    # VMware provider config
    server.vm.provider "vmware_desktop" do |vb|
      vb.gui = false
      vb.memory = "1024"
      vb.cpus = 1
    end

    # Provisioning scripts
    server.vm.provision "shell", path: "scripts/startup.sh"
  end
end
