Vagrant.configure("2") do |config|

  # SERVER NODE
  config.vm.define "mbelouarS" do |server|
    server.vm.box = "spox/ubuntu-arm"
    server.vm.box_version = "1.0.0"
    server.vm.hostname = "mbelouarS"

    # Networking
    server.vm.network "private_network", ip: "192.168.56.110"

    # Synced folder
    server.vm.synced_folder "./token", "/vagrant/token"

    # VMware provider config
    server.vm.provider "vmware_desktop" do |vb|
      vb.gui = false
      vb.memory = "1024"
      vb.cpus = 1
    end

    # Provisioning scripts
    server.vm.provision "shell", path: "scripts/k3s.sh"
    server.vm.provision "shell", path: "scripts/kubectl.sh"
    server.vm.provision "shell", path: "scripts/copy_token.sh"

    server.vm.provision "shell", path: "scripts/label_worker.sh", run: "always", :after => :all
  end

  # WORKER NODE
  config.vm.define "mbelouarSW", depends_on: ["mbelouarS"] do |worker|
    worker.vm.box = "spox/ubuntu-arm"
    worker.vm.box_version = "1.0.0"
    worker.vm.hostname = "mbelouarSW"

    # Networking
    worker.vm.network "private_network", ip: "192.168.56.111"

    # Synced folder
    worker.vm.synced_folder "./token", "/vagrant/token"

    # VMware provider config
    worker.vm.provider "vmware_desktop" do |vb|
      vb.gui = false
      vb.memory = "1024"
      vb.cpus = 1
    end

    # Provisioning scripts
    worker.vm.provision "shell", path: "scripts/worker.sh"

  end

end
