Vagrant.configure("2") do |config|

  # SERVER NODE
  config.vm.define "mbelouarS" do |server|
    server.vm.box = "ubuntu/focal64"
    server.vm.hostname = "mbelouarS"

    # Create a forwarded port mapping which allows access to a specific port
    # server.vm.network "forwarded_port", guest: 80, host: 8080
    # server.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"
    server.vm.network "private_network", ip: "192.168.56.110"

    # create a synced folder that is shared between the host and guest
    server.vm.synced_folder "./token", "/vagrant"
    # server.vm.synced_folder ".", "/vagrant", disabled: true

    # provider-specific configuration so you can fine-tune various
    server.vm.provider "virtualbox" do |vb|
      vb.name = "mbelouarS_VM"
      vb.gui = false
      vb.memory = "1024"
      vb.cpus = 1
    end
      # Enable provisioning with a shell script. This is a simple example.
    server.vm.provision "shell", path: "scripts/kubectl.sh"
    server.vm.provision "shell", path: "scripts/k3s.sh"
    server.vm.provision "shell", path: "scripts/copy_token.sh"
    server.vm.provision "shell", path: "scripts/validate_cluster.sh", run: "always"
    
  end

  # WORKER NODE
  config.vm.define "mbelouarSW" do |worker|
    worker.vm.box = "ubuntu/focal64"
    worker.vm.hostname = "mbelouarSW"

    # Create a forwarded port mapping which allows access to a specific port
    # worker.vm.network "forwarded_port", guest: 80, host: 8080
    # worker.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"
    worker.vm.network "private_network", ip: "192.168.56.111"

    # create a synced folder that is shared between the host and guest
    worker.vm.synced_folder "./token", "/vagrant"

    # provider-specific configuration so you can fine-tune various
    worker.vm.provider "virtualbox" do |vb|
      vb.name = "mbelouarSW_VM"
      vb.gui = false
      vb.memory = "1024"
      vb.cpus = 1
    end
    
    # Enable provisioning with a shell script. This is a simple example.
    worker.vm.provision "shell", path: "scripts/worker_join.sh"
    # worker.vm.provision "shell", inline: <<-SHELL
    #   apt-get update
    #   apt-get install -y apache2
    # SHELL

  end

end
